### ISSUE TITLE
Please don't hardcode 

### ISSUE THREAD

**Issue by rajpatel8** [absolute-viper/Project_Final_Year#5]
@absolute-viper , 
Please change the **path in unzipped** file at line 4, to access the data from **GCS Bucket** instead of local disk. 
As I am starting the training the model from tonight itself.

**Comment by absolute-viper** [comment]
Gand Mara Chutiye

**Comment by rajpatel8** [comment]
Please consider my request.

**Comment by absolute-viper** [comment]
Bheekh Maang
Naak Ragad
Fir Consider karunga
